# Assembly of the test sets translated by the class

This code allowed us to assemble and process the test_set snippets translated by the class

In [242]:
import pandas as pd 
import string
import calendar
import string 


import pandas as pd 
import gensim
from gensim.models import Word2Vec


import nltk
from nltk import pos_tag, word_tokenize

## Concatention des sous_df_set

In [243]:
df=pd.read_excel("avis_1_traduit.xlsx")
df.head(5)

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
0,5,brahim--k-131532,"Meilleurs assurances, prix, solutions, écoute,...",Direct Assurance,auto,train,06/09/2021,01/09/2021,"Best insurance, price, solutions, listening, s...",NaN,NaN
1,4,bernard-g-112497,"je suis globalement satisfait , sauf que vous ...",Direct Assurance,auto,train,03/05/2021,01/05/2021,"I am generally satisfied, except that you have...",NaN,NaN
2,5,virginie-t-107352,Prix tres abordable plusieurs options s'offren...,Direct Assurance,auto,train,21/03/2021,01/03/2021,Very affordable price Several options are avai...,NaN,NaN
3,4,boulain-f-116580,"je satisfait du service, une réponse très rapi...",L'olivier Assurance,auto,train,10/06/2021,01/06/2021,"I satisfy the service, a very fast response fr...",NaN,NaN
4,1,ouaille31-51798,"Client depuis plus de 25 ans, très déçu de cet...",Matmut,auto,train,29/01/2017,01/01/2017,"Customer for more than 25 years, very disappoi...",NaN,NaN

In [244]:
s=len(df)
for i in range(2,36):
    print(i)
    df_n=pd.read_excel("avis_"+str(i)+"_traduit.xlsx")
    s+=len(df_n)
    

    
    df=pd.concat((df,df_n))

print(s)
df

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
34435

,note,auteur,avis,assureur,produit,type,date_publication,date_exp,avis_en,avis_cor,avis_cor_en
0,5.0,brahim--k-131532,"Meilleurs assurances, prix, solutions, écoute,...",Direct Assurance,auto,train,06/09/2021,01/09/2021,"Best insurance, price, solutions, listening, s...",NaN,NaN
1,4.0,bernard-g-112497,"je suis globalement satisfait , sauf que vous ...",Direct Assurance,auto,train,03/05/2021,01/05/2021,"I am generally satisfied, except that you have...",NaN,NaN
2,5.0,virginie-t-107352,Prix tres abordable plusieurs options s'offren...,Direct Assurance,auto,train,21/03/2021,01/03/2021,Very affordable price Several options are avai...,NaN,NaN
3,4.0,boulain-f-116580,"je satisfait du service, une réponse très rapi...",L'olivier Assurance,auto,train,10/06/2021,01/06/2021,"I satisfy the service, a very fast response fr...",NaN,NaN
4,1.0,ouaille31-51798,"Client depuis plus de 25 ans, très déçu de cet...",Matmut,auto,train,29/01/2017,01/01/2017,"Customer for more than 25 years, very disappoi...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
430,NaN,mamybouly-129360,"Bonjour, j'ai une mauvaise expérience avec la ...",Sma,garantie-decennale,test,24/08/2021,01/08/2021,"Hello, I have a bad experience with the Socoba...","Bonjour, j'ai une mauvaise expérience avec la ...","Hello, I have a bad experience with the Socoba..."
431,NaN,tarti-88637,Entreprise très impactée par le covid- secteur...,Allianz,assurances-professionnelles,test,18/05/2021,01/05/2021,Company very impacted by the covid- event sect...,Entreprise très impactée par le covid- secteur...,NaN
432,NaN,victor-109599,"Suite a un cambriolage le 22/01/2021, je suis ...",Allianz,assurances-professionnelles,test,08/04/2021,01/04/2021,"Following a burglary on 01/22/2021, I am still...","Suite a un cambriolage le 22/01/2021, je suis ...",NaN
433,NaN,lkio-110907,"Bonjour,\n\nJe constate qu'entre le moment de ...",Generali,assurances-professionnelles,test,19/04/2021,01/04/2021,"Hello,\n\nI note that between the time of my r...","Bonjour,\n\nJe constate qu'entre le moment de ...",NaN
434,NaN,padpad-105625,Longtemps je n'ai eu besoin de rien et me suis...,AXA,assurances-professionnelles,test,05/03/2021,01/03/2021,For a long time I did not need anything and I ...,Longtemps je n'ai eu besoin de rien et me suis...,NaN

In [245]:
df.drop(["avis_cor","avis_cor_en","date_exp"],axis=1,inplace=True)
df.head(2)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en
0,5.0,brahim--k-131532,"Meilleurs assurances, prix, solutions, écoute,...",Direct Assurance,auto,train,06/09/2021,"Best insurance, price, solutions, listening, s..."
1,4.0,bernard-g-112497,"je suis globalement satisfait , sauf que vous ...",Direct Assurance,auto,train,03/05/2021,"I am generally satisfied, except that you have..."

In [247]:
print(df.shape)
df.dropna(inplace=True)
print(df.shape)

(34435, 8)
(24102, 8)

In [248]:
df.reset_index(inplace=True,drop=True)
df.head(2)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en
0,5.0,brahim--k-131532,"Meilleurs assurances, prix, solutions, écoute,...",Direct Assurance,auto,train,06/09/2021,"Best insurance, price, solutions, listening, s..."
1,4.0,bernard-g-112497,"je suis globalement satisfait , sauf que vous ...",Direct Assurance,auto,train,03/05/2021,"I am generally satisfied, except that you have..."

## Nettoyage du  test SET

In [249]:
def __get_day_date__(x):
    return x.split("/")[0]
def __get_day_mounth__(x):
    return x.split("/")[1]
def __get_day_year__(x):
    return x.split("/")[2]


def __encodeLatin_DecodeUTF8__(x):
    try:    
        return x.encode("latin1").decode("utf_8")
    except: 
        return None

def __clean_BREAKLINE__(x):
    return x.replace("\r","").replace("\n"," ").replace("_x000D_","").replace("\xa0en","")

def __remove_ponctuation__(x):
    for punctuation in string.punctuation:
        x=x.replace(punctuation,"")
    return x

def __lower__(x):
    return x.lower().strip()

### Netoyage assureur

In [250]:
df.assureur=df.assureur.apply(lambda x:__encodeLatin_DecodeUTF8__(x))

print(len(df))
df.dropna(subset=["assureur"],inplace=True)
# df.fillna("")
print(len(df))


df.assureur=df.assureur.apply(lambda x:__clean_BREAKLINE__(x))
df.assureur=df.assureur.apply(lambda x:__remove_ponctuation__(x))
# # tout en minuscule
df.assureur=df.assureur.apply(lambda x:__lower__(x))

24102
22725

### Nettoyage produit

In [251]:
df.produit=df.produit.apply(lambda x:__encodeLatin_DecodeUTF8__(x))

print(len(df))
df.dropna(subset=["produit"],inplace=True)
print(len(df))


df.produit=df.produit.apply(lambda x:__clean_BREAKLINE__(x))
df.produit=df.produit.apply(lambda x:__remove_ponctuation__(x))
# tout en minuscule
df.produit=df.produit.apply(lambda x:__lower__(x))

22725
22725

### Nettoyage avis

In [252]:
# Encodage et nettoyage des avis
df.avis=df.avis.apply(lambda x:__encodeLatin_DecodeUTF8__(x))

print(len(df))
df.dropna(subset=["avis"],inplace=True)
df.fillna("")
print(len(df))


df.avis=df.avis.apply(lambda x:__clean_BREAKLINE__(x))
df.avis=df.avis.apply(lambda x:__remove_ponctuation__(x))
df.avis=df.avis.apply(lambda x:__lower__(x))

22725
1308

### Nettoyage date

In [253]:
df["day_date"]=None
df["day_mounth"]=None
df["day_year"]=None

df["day_date"]=df.apply(lambda x:__get_day_date__(x.date_publication),axis=1)
df["day_mounth"]=df.apply(lambda x:__get_day_mounth__(x.date_publication),axis=1)
df["day_year"]=df.apply(lambda x:__get_day_year__(x.date_publication),axis=1)

In [254]:
mois_convertion={"01":"janvier","02":"février","03":"mars","04":"avril","05":"mai",
"06":"juin","07":"juillet","08":"août","09":"septembre","10":"octobre","11":"novembre","12":"décembre"}

def __convertion_int_to_name__(x):
    return mois_convertion[x]

df['day_mounth'] = df['day_mounth'].apply(lambda x: __convertion_int_to_name__(x))

df.head(2)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en,day_date,day_mounth,day_year
15,5.0,youssef-n-109465,je suis satisfait de direct assurance neanmoin...,direct assurance,auto,train,07/04/2021,I am satisfied with direct insurance neverthel...,07,avril,2021
30,5.0,alain-c-96661,bonjour je suis passer par les furetscom plusi...,april moto,moto,train,29/08/2021,"Hello, I am going through the ferrets.com, sev...",29,août,2021

In [255]:
print(df.shape)
df.dropna(subset="avis_en",inplace=True)
df.reset_index(inplace=True,drop=True)
print(df.shape)

(1308, 11)
(1308, 11)

## Vectorisation

In [257]:
def __token__(x):
    return x.split(" ")

def __repartitionMots__(avis):
    """Fonction permettant de ne garder que les noms communs, adjectifs et verbes d'une liste de string en ANGLAIS"""
    #si prend en entrée une phrase :
    #avis=nltk.word_tokenize(avis)

    listTAG = nltk.pos_tag(avis)

    listRetour = []
    for i in range(len(listTAG)):
        if listTAG[i][1]=="RB" or listTAG[i][1]=="NN" or listTAG[i][1]=="VBD" or listTAG[i][1]=="JJ" or listTAG[i][1]=="VB":
            listRetour.append(listTAG[i][0])    

    return listRetour

def __create_average_WordtoVec__(token): 

    try: 
        # token=x.split(" ")
        while '' in token: 
            token.remove('')

        return sum(model1.wv[token])/len(token)
    except:
        return None

def __get_vecteur_element__(x):
    return x[i]

### Re-creer le modele

In [258]:
train=pd.read_csv("../train_vect.csv")

In [259]:
# get list all rating word
words=""
for a in train.avis_en:   
    words=words+" "+"".join(a)

words=words.strip()

In [260]:
# tokenize list
import nltk
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
token_words=tokenizer.tokenize(words)

token_words=set(token_words)

token_words_reduce=__repartitionMots__(token_words)

In [261]:
# vectorise list
model1 = gensim.models.Word2Vec([token_words_reduce], min_count = 1,
                              vector_size = 10, window = 5)

### Application du modele pour vectoriser

In [262]:
df["token_avis_en"]=None
df["token_avis_en"]=df.avis_en.apply(lambda x: __repartitionMots__(__token__(x)) )
df.head(2)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en,day_date,day_mounth,day_year,token_avis_en
0,5.0,youssef-n-109465,je suis satisfait de direct assurance neanmoin...,direct assurance,auto,train,07/04/2021,I am satisfied with direct insurance neverthel...,07,avril,2021,"[satisfied, direct, insurance, nevertheless, h..."
1,5.0,alain-c-96661,bonjour je suis passer par les furetscom plusi...,april moto,moto,train,29/08/2021,"Hello, I am going through the ferrets.com, sev...",29,août,2021,"[ferrets.com,, several, proposal, appeared, me..."

In [264]:
# Suppression des mots non reconnaissable par le modèle

def __suppression_mot_non_vectorisable__(x):
    
    for i in x: 
        if i not in token_words_reduce:
            x.remove(i)
        elif i=="":
            x.remove(i)

    return x


df.token_avis_en.apply(lambda x: __suppression_mot_non_vectorisable__(x))

0       [satisfied, direct, insurance, nevertheless, b...
1         [several, proposal, me,, simple,, quick, level]
2       [flee, quickly, first, climb, year\n\n-, had, ...
3       [sufficient, satisfied, home, unfortunately, u...
4       [very, interesting, especially, relation, phys...
                              ...
1303                                                   []
1304                                                   []
1305                                                   []
1306    [practical\nImpeccable, phone, service, little...
1307    [satisfied, listen, advise, ones., put, insura...
Name: token_avis_en, Length: 1308, dtype: object

In [268]:
# créer colonne vecteur_moyenne
df["vecteur_moyen"]=df.apply(lambda x: __create_average_WordtoVec__(x.token_avis_en),axis=1)
print(df.shape)
df.head(2)

(1308, 13)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en,day_date,day_mounth,day_year,token_avis_en,vecteur_moyen
0,5.0,youssef-n-109465,je suis satisfait de direct assurance neanmoin...,direct assurance,auto,train,07/04/2021,I am satisfied with direct insurance neverthel...,07,avril,2021,"[satisfied, direct, insurance, nevertheless, b...","[-0.0029793493, 0.025995314, -0.010212362, 0.0..."
1,5.0,alain-c-96661,bonjour je suis passer par les furetscom plusi...,april moto,moto,train,29/08/2021,"Hello, I am going through the ferrets.com, sev...",29,août,2021,"[several, proposal, me,, simple,, quick, level]",None

In [269]:
print(df.shape)
df.dropna(inplace=True)
df.reset_index(inplace=True,drop=True)
print(df.shape)

(1308, 13)
(659, 13)

In [270]:
# créer colonne elements du vecteur 

for i in range(len(df.vecteur_moyen[0])):
    col_name="vecteur_"+str(i)

    df[col_name]=None
    df[col_name]=df.vecteur_moyen.apply(lambda x: __get_vecteur_element__(x) )

df.head(2)

,note,auteur,avis,assureur,produit,type,date_publication,avis_en,day_date,day_mounth,...,vecteur_0,vecteur_1,vecteur_2,vecteur_3,vecteur_4,vecteur_5,vecteur_6,vecteur_7,vecteur_8,vecteur_9
0,5.0,youssef-n-109465,je suis satisfait de direct assurance neanmoin...,direct assurance,auto,train,07/04/2021,I am satisfied with direct insurance neverthel...,07,avril,...,-0.002979,0.025995,-0.010212,0.012139,0.010351,-0.015461,-0.010013,-0.006830,0.013929,0.028857
1,3.0,kamel-b-108579,je suis suffisant satisfait de vos prestations...,direct assurance,auto,train,30/03/2021,I am sufficient satisfied with your services. ...,30,mars,...,-0.008020,0.020905,0.027659,-0.000744,0.027265,-0.012828,0.004051,-0.005684,0.018480,-0.012093

In [271]:
df.to_csv("../test_final.csv",index=False)