# Supervised Learning

The code below creates the models using the PyCaret library. The models are saved and will be used in the main code (to avoid the execution being too long).

In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
df=pd.read_csv("../datasets/train_vect.csv")
df.head(2)

,note,auteur,avis,assureur,produit,day_date,day_mounth,day_year,avis_en,token_avis_en,vecteur_moyen,vecteur_0,vecteur_1,vecteur_2,vecteur_3,vecteur_4,vecteur_5,vecteur_6,vecteur_7,vecteur_8,vecteur_9
0,1,rezo31-62544,generali assurances vie patrimoine très mauvai...,generali,vie,21,mars,2018,generali life insurance patrimony very bad cus...,"['generali', 'life', 'insurance', 'patrimony',...",[ 0.00284756 0.03417591 0.01852238 -0.016715...,0.002848,0.034176,0.018522,-0.016716,0.018529,-0.003764,0.030136,0.004864,0.006238,0.010565
1,5,re-v-109323,totalement satisfaite de la qualité des prises...,lolivier assurance,auto,6,avril,2021,totally satisfied with the quality of the tele...,"['totally', 'satisfied', 'quality', 'telephone...",[ 0.00370687 -0.00772468 -0.01492408 -0.007305...,0.003707,-0.007725,-0.014924,-0.007306,0.013408,-0.001732,0.021056,-0.004091,0.006557,0.010996

In [3]:
df.drop(["auteur","avis","vecteur_moyen","avis_en","token_avis_en"],axis=1,inplace=True)

In [4]:
s = setup(df, target = 'note')

In [5]:
best = compare_models(sort = 'RMSE',n_select = 5)

In [6]:
# evaluate_model(best)

In [7]:
import pickle 

pickle.dump( best[0], open( "regression_0.p", "wb" ) )
pickle.dump( best[1], open( "regression_1.p", "wb" ) )
pickle.dump( best[2], open( "regression_2.p", "wb" ) )
pickle.dump( best[3], open( "regression_3.p", "wb" ) )
pickle.dump( best[4], open( "regression_4.p", "wb" ) )

In [8]:
pickle.load(open("regression_0.p","rb"))

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=3265, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)